apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.deployment.name }}
          image: "{{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.deployment.containerPort }}
          env:
            - name: VITE_API_BASE_URL
              value: "/api"