apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.deployment.name }}
spec:
  replicas: {{ .Values.zookeeper.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.zookeeper.deployment.name }}
          image: "{{ .Values.zookeeper.deployment.image }}:{{ .Values.zookeeper.deployment.tag }}"
          ports:
            - containerPort: {{ .Values.zookeeper.deployment.containerPort }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 10